// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcdqwclfyynostnfijvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZHF3Y2xmeXlub3N0bmZpanZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTI0MjMsImV4cCI6MjA2NzQ2ODQyM30.zPwIhjPj6RNMxP06cwOeuHYJz0PAIObasuJboKrNeFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});